### ISSUE TITLE
非常好用，但是能否在增加两个小功能！

### ISSUE THREAD

**Issue by SoTender** [Masterain98/PlexMuxy#2]
1.添加音频语言信息，因为我也是拿来封装动漫，基本都是日语；
如果音频没有语言信息的话，plex这里显示不够美观（强迫症！

![QQ截图20230704093336](https://github.com/Masterain98/PlexMuxy/assets/127156952/c62ea452-4a4c-4992-97b0-4a4491bb62b7)

对应到mkvtoolnix这里音频语言为ja：
![QQ截图20230704093627](https://github.com/Masterain98/PlexMuxy/assets/127156952/0527c98c-f955-4db4-bc59-022709cde840)

这里为ja的情况下，plex能完美显示：
![QQ截图20230704095225](https://github.com/Masterain98/PlexMuxy/assets/127156952/95e339bd-2523-48f0-bb74-838890b750ec)

==============================================================================

2.多字幕情况下，能不能只开启一个【默认轨道】字幕（简体/繁体），或者只开启一个强制显示轨道！

![QQ截图20230704094430](https://github.com/Masterain98/PlexMuxy/assets/127156952/b9d89022-59dc-4977-a11a-66a194f512a1)
或者这样：
![QQ截图20230704094450](https://github.com/Masterain98/PlexMuxy/assets/127156952/87d2746b-4a77-45bb-9393-07f99544df36)

**Comment by SoTender** [comment]
第1个请求功能：

建议用户可以自定义，是否默认强制更改音频语言；
因为我发现有些音频不是und，反而是其他错误的语言；
所以在自己确定都是动漫的情况，强制默认更改为ja（日语）就好了！

第2个请求功能：

我是emby/plex多修用户的关系吧，这个主要是为了emby也能更好的显示。
字幕轨道名称改成【Chinese Simplified/Chinese Traditional】，
是由于我给emby的开发人员建议，在中文chi的条件下，用轨道名称的关键词来区分中文简繁！

关键词 ： Simplified/Traditional/简体/繁体等，现在也已经支持。

所以改成这两个轨道名称，在不影响plex的情况下，有助于兼容emby！

但是本人能力有限，其他地方改不来（哈哈哈哈），所以就看大佬方便update一下嘛

下面是对应条件下，字幕在emby里的显示效果：
默认单字幕轨：
![默认单字幕轨](https://github.com/Masterain98/PlexMuxy/assets/127156952/57341b90-567a-4272-9c93-b4b9c9b5cca4)
默认单字幕轨 - 效果：
![默认单字幕轨 - 效果](https://github.com/Masterain98/PlexMuxy/assets/127156952/6bc8070c-bdcf-42ac-a728-a5f5e3278855)

默认双字幕轨、单字幕强制
![默认双字幕轨、单字幕强制](https://github.com/Masterain98/PlexMuxy/assets/127156952/8737865c-7540-4d78-b256-f821604d9399)
默认双字幕轨、单字幕强制 - 效果
![默认双字幕轨、单字幕强制 - 效果](https://github.com/Masterain98/PlexMuxy/assets/127156952/991e2d60-57db-43cc-9b66-2ec83561dbd2)

**Comment by Masterain98** [comment]
> 因为我发现有些音频不是und，反而是其他错误的语言

给一个有该问题的资源链接

**Comment by SoTender** [comment]
> 给一个有该问题的资源链接

BDrip的动漫没有这个问题，
我主要想内封一些不可描述的动漫。。。
这个可以说嘛。。。

但是那个每个字幕的字体不相同，
要是把所有字体都封进视频，
plex播放没问题，秒播放。

emby播放就会慢很多，可能要加载所有字体导致的。

要是能根据每个字幕样式，内封对应字体就好了

（保证字体名称和字幕样式名称一致的情况下）
（根据Fonts文件里存在的字体匹配ass字幕样式里的）


因为我发现，如果内封的【字体文件名称】（不是安装的字体名称）跟字幕样式里的名称不一致时，

plex/emby app客户端有一定概率不会加载该字体样式！

我目前就先给手动给【字体文件名称】改成【字体安装名称】
（严格一致，尽量避免上面那个问题）

**Comment by SoTender** [comment]
上面我说的那个好像还有个小问题，就是有的字体。字幕样式里没有，反而出现在某一特定行，我不知道这种情况改怎么办。。。

样式1： A字体
字幕行X： 样式1 fn B字体

不知道我又没有表述清楚

这种能不能匹配字幕样式里的字体+fn后面的字体名称呢

**Comment by Masterain98** [comment]
> 样式1： A字体 字幕行X： 样式1 fn B字体

这是选择了B字体作为覆盖

> 要是把所有字体都封进视频， plex播放没问题，秒播放。
> emby播放就会慢很多，可能要加载所有字体导致的。

Plex的策略是将资源全部进行实时编码，如果有硬件加速的话体验会是很好的。emby没有用过，不清楚。

> 因为我发现，如果内封的【字体文件名称】（不是安装的字体名称）跟字幕样式里的名称不一致时，
> plex/emby app客户端有一定概率不会加载该字体样式！

我的经验是，更有可能是 ass 里写错了字幕名称。理论上应当是**字体名称**，而不是**字体文件名称**。


ASS 没有什么强制性的标准，不同播放器会有不同的渲染策略，对 ASS 文件语法读取也有差异，不好处理。

**Comment by SoTender** [comment]
> 这是选择了B字体作为覆盖

那这种情况，能根据ass里的字体样式+覆盖的字体，选择性内封字体嘛


> Plex的策略是将资源全部进行实时编码，如果有硬件加速的话体验会是很好的。emby没有用过，不清楚。

Plex web/windowe客户端/app客户端，ass字幕加载内封字体的效果都不错。
Emby web不能加载内封字体，客户端跟Plex基本没有区别。

> 我的经验是，更有可能是 ass 里写错了字幕名称。理论上应当是**字体名称**，而不是**字体文件名称**。

我遇到的不能加载字体的情况：

字体文件名称是：A_GBK_0.ext
实际字体名称是：A_GBK
ASS字幕样式对应的字体名称是：A_GBK

这时候plex/emby有一定概率在首次播放的时候不会加载该字体，
但是重开（清除缓存）又有一定概率加载字体样式。（app 客户端比较容易遇到）

感觉有点玄学，所以我先改字体文件名。

**Comment by SoTender** [comment]
> 这是选择了B字体作为覆盖

我才发现，我白嫖的800部BDrip动漫，好像都内封了专用的字体？

![QQ截图20230714071907](https://github.com/Masterain98/PlexMuxy/assets/127156952/a48357ce-d916-46b9-9f87-70f3b93e184c)

但是字体好像都挺小的？（原来叫子集化）


我就说他们都说只收BDrip，原来是没有字幕特效的烦恼哇。

但是我好奇动漫花园的字幕发布组，也是用的这个工具？
看内封的样式，跟你写的这个差不多？

**Comment by Masterain98** [comment]
> 但是字体好像都挺小的？（原来叫子集化）

https://vcb-s.com/archives/1114
https://bbs.acgrip.com/forum.php?mod=viewthread&tid=3848&highlight=FontLoaderSub
我个人不在意储存容量所以不做字体子集。字幕组往往会随着新番更新而更新带字幕的剧集，所以需要在意单集的容量。

> 我就说他们都说只收BDrip，原来是没有字幕特效的烦恼哇。

你理解错了。BD 盘里只会有类似于 CC 字幕的源语言字幕文件，提取也是压制过程中的步骤。字幕特效都是字幕组后期做的。

> 但是我好奇动漫花园的字幕发布组，也是用的这个工具？ 看内封的样式，跟你写的这个差不多？

每个字幕组的工作流程都不一样

**Comment by SoTender** [comment]
> https://vcb-s.com/archives/1114 https://bbs.acgrip.com/forum.php?mod=viewthread&tid=3848&highlight=FontLoaderSub 我个人不在意储存容量所以不做字体子集。字幕组往往会随着新番更新而更新带字幕的剧集，所以需要在意单集的容量。
> 

自己内封字体确实没必要弄子集化，有字体附件就能加载了

**Comment by Masterain98** [comment]
尝试一下这个版本 https://github.com/Masterain98/PlexMuxy/releases/tag/2023.7.16

第一次运行后不要直接执行任务，关掉程序后进入文档库目录，找到 `PlexMuxy.json` 并修改参数

- 不再需要将程序放置于视频项目目录，可以运行在任何路径下，手动填入项目路径即可
- `["mkvmerge"]["path"]` 中设置你的 `mkvmerge.exe` 路径
- 如果需要自动解压 RAR 压缩包，需要设置 `["Font"]["Unrar_Path"]` 路径
- `DefaultLanguage` 中可以设置为 `["Subtitle"]["Keyword"]` 中的小写键名（比如`chs`或`jp_sc`），除了该语言以外的其它字幕将不会设置为字幕的默认轨道
- **如果 `mkv` 文件中已包含的音轨没有设置语言，程序将询问用户设置为何种语言**
